### ISSUE TITLE
Batch update UI

### ISSUE THREAD

**Issue by anandaroop** [artsy/rosalind#87]
The batch update will be specified in a modal overlay that allows a user to select genes and assign values to them. Upon submission these gene/value pairs will be applied asynchronously to all artworks in the current selection.

## Todo

- [x] Create a full screen modal component
   - [x] Animate in and out, per discussion with @brentcas 
- [x] Add zero-state UI
  - [x] Wire up gene autocomplete
  - [x] Other buttons and labels
  - [x] initial form state should show a common genome for selected works
    - [x] derive the list of genes that are shared by currently selected works
    - [x] default to that set of genes, with null values, in the initial form
    - [x] if possible, have a default placeholder of "multiple" null-valued genes

- [x] Add gene-adding UI
  - [x] Add gene widget based on selection
  - [x] Dynamically style widget based on gene value
  - [x] add strikethrough to zero-valued genes
- [x] Add confirmation dialog for submission 
- [x] Send the submitted values to the batch update controller

## Modal in zero-state

![modal](https://cloud.githubusercontent.com/assets/140521/25749176/9db82166-317b-11e7-8175-97ccda20bc84.png)

## Specifying genes and values

![genes](https://cloud.githubusercontent.com/assets/140521/25749375/46301a7e-317c-11e7-97bd-7eef559dde05.png)

## Submitting the update to the queue

![submit](https://cloud.githubusercontent.com/assets/140521/25749379/4d9bcd08-317c-11e7-89da-a9b4261a732d.png)
